// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package operation

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	api "github.com/violin0622/grpc-apple/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AppleServiceClient is the client API for AppleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppleServiceClient interface {
	DescribeApple(ctx context.Context, in *DescribeAppleRequest, opts ...grpc.CallOption) (*api.Apple, error)
	CreateApple(ctx context.Context, in *CreateAppleRequest, opts ...grpc.CallOption) (*api.Apple, error)
	UpdateApple(ctx context.Context, in *UpdateAppleRequest, opts ...grpc.CallOption) (*api.Apple, error)
	ModifyApple(ctx context.Context, in *ModifyAppleRequest, opts ...grpc.CallOption) (*api.Apple, error)
	DestroyApple(ctx context.Context, in *DestroyAppleRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type appleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppleServiceClient(cc grpc.ClientConnInterface) AppleServiceClient {
	return &appleServiceClient{cc}
}

func (c *appleServiceClient) DescribeApple(ctx context.Context, in *DescribeAppleRequest, opts ...grpc.CallOption) (*api.Apple, error) {
	out := new(api.Apple)
	err := c.cc.Invoke(ctx, "/operation.AppleService/DescribeApple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appleServiceClient) CreateApple(ctx context.Context, in *CreateAppleRequest, opts ...grpc.CallOption) (*api.Apple, error) {
	out := new(api.Apple)
	err := c.cc.Invoke(ctx, "/operation.AppleService/CreateApple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appleServiceClient) UpdateApple(ctx context.Context, in *UpdateAppleRequest, opts ...grpc.CallOption) (*api.Apple, error) {
	out := new(api.Apple)
	err := c.cc.Invoke(ctx, "/operation.AppleService/UpdateApple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appleServiceClient) ModifyApple(ctx context.Context, in *ModifyAppleRequest, opts ...grpc.CallOption) (*api.Apple, error) {
	out := new(api.Apple)
	err := c.cc.Invoke(ctx, "/operation.AppleService/ModifyApple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appleServiceClient) DestroyApple(ctx context.Context, in *DestroyAppleRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/operation.AppleService/DestroyApple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppleServiceServer is the server API for AppleService service.
// All implementations must embed UnimplementedAppleServiceServer
// for forward compatibility
type AppleServiceServer interface {
	DescribeApple(context.Context, *DescribeAppleRequest) (*api.Apple, error)
	CreateApple(context.Context, *CreateAppleRequest) (*api.Apple, error)
	UpdateApple(context.Context, *UpdateAppleRequest) (*api.Apple, error)
	ModifyApple(context.Context, *ModifyAppleRequest) (*api.Apple, error)
	DestroyApple(context.Context, *DestroyAppleRequest) (*empty.Empty, error)
	mustEmbedUnimplementedAppleServiceServer()
}

// UnimplementedAppleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAppleServiceServer struct {
}

func (*UnimplementedAppleServiceServer) DescribeApple(context.Context, *DescribeAppleRequest) (*api.Apple, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeApple not implemented")
}
func (*UnimplementedAppleServiceServer) CreateApple(context.Context, *CreateAppleRequest) (*api.Apple, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApple not implemented")
}
func (*UnimplementedAppleServiceServer) UpdateApple(context.Context, *UpdateAppleRequest) (*api.Apple, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApple not implemented")
}
func (*UnimplementedAppleServiceServer) ModifyApple(context.Context, *ModifyAppleRequest) (*api.Apple, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyApple not implemented")
}
func (*UnimplementedAppleServiceServer) DestroyApple(context.Context, *DestroyAppleRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyApple not implemented")
}
func (*UnimplementedAppleServiceServer) mustEmbedUnimplementedAppleServiceServer() {}

func RegisterAppleServiceServer(s *grpc.Server, srv AppleServiceServer) {
	s.RegisterService(&_AppleService_serviceDesc, srv)
}

func _AppleService_DescribeApple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeAppleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppleServiceServer).DescribeApple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operation.AppleService/DescribeApple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppleServiceServer).DescribeApple(ctx, req.(*DescribeAppleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppleService_CreateApple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppleServiceServer).CreateApple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operation.AppleService/CreateApple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppleServiceServer).CreateApple(ctx, req.(*CreateAppleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppleService_UpdateApple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppleServiceServer).UpdateApple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operation.AppleService/UpdateApple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppleServiceServer).UpdateApple(ctx, req.(*UpdateAppleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppleService_ModifyApple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyAppleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppleServiceServer).ModifyApple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operation.AppleService/ModifyApple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppleServiceServer).ModifyApple(ctx, req.(*ModifyAppleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppleService_DestroyApple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyAppleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppleServiceServer).DestroyApple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operation.AppleService/DestroyApple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppleServiceServer).DestroyApple(ctx, req.(*DestroyAppleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "operation.AppleService",
	HandlerType: (*AppleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeApple",
			Handler:    _AppleService_DescribeApple_Handler,
		},
		{
			MethodName: "CreateApple",
			Handler:    _AppleService_CreateApple_Handler,
		},
		{
			MethodName: "UpdateApple",
			Handler:    _AppleService_UpdateApple_Handler,
		},
		{
			MethodName: "ModifyApple",
			Handler:    _AppleService_ModifyApple_Handler,
		},
		{
			MethodName: "DestroyApple",
			Handler:    _AppleService_DestroyApple_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/operation/operations.proto",
}
